import Foundation
import PAWorkspace
import PASkills

public struct AgentCommand: Sendable, Equatable {
    public let name: String
    public let arguments: [String]
    public init(name: String, arguments: [String] = []) { self.name = name; self.arguments = arguments }
}

public enum CommandError: Error, Sendable, Equatable, LocalizedError {
    case emptyCommand
    case unterminatedQuote
    case invalidEscape
    case unknownCommand(String)
    case invalidArguments(String)

    public var errorDescription: String? {
        switch self {
        case .emptyCommand:
            return "Enter a command."
        case .unterminatedQuote:
            return "Unterminated quote. Close the quote and try again."
        case .invalidEscape:
            return "The command ends with an incomplete escape. Add the escaped character or remove the trailing backslash."
        case .unknownCommand(let name):
            return "Unknown command: \(name). Type 'help' to list available commands."
        case .invalidArguments(let usage):
            return "Invalid arguments. Usage: \(usage)"
        }
    }
}

public struct CommandResult: Sendable, Equatable {
    public let stdout: String
    public let stderr: String
    public let exitCode: Int32
    public var success: Bool { exitCode == 0 }
    public init(stdout: String = "", stderr: String = "", exitCode: Int32 = 0) { self.stdout = stdout; self.stderr = stderr; self.exitCode = exitCode }
}

public struct CommandContext: Sendable {
    public let workspace: AgentWorkspace
    public let workingDirectory: String
    public init(workspace: AgentWorkspace, workingDirectory: String = "") { self.workspace = workspace; self.workingDirectory = workingDirectory }
}

public typealias CommandHandler = @Sendable (AgentCommand, CommandContext) async throws -> CommandResult

public struct CommandRegistry: Sendable {
    private let handlers: [String: CommandHandler]
    public init(handlers: [String: CommandHandler] = [:]) { self.handlers = handlers }
    public func registering(_ name: String, handler: @escaping CommandHandler) -> CommandRegistry {
        var copy = handlers; copy[name] = handler; return CommandRegistry(handlers: copy)
    }
    public func contains(_ name: String) -> Bool { handlers[name] != nil }
    /// Terminal output is untrusted and may be generated by large files or tools.
    /// Bound each stream centrally so every command inherits the same UI/memory limit.
    public static let maximumOutputBytes = 64 * 1024

    public func execute(_ command: AgentCommand, context: CommandContext) async throws -> CommandResult {
        guard let handler = handlers[command.name] else { throw CommandError.unknownCommand(command.name) }
        let result = try await handler(command, context)
        return CommandResult(
            stdout: Self.bounded(result.stdout),
            stderr: Self.bounded(result.stderr),
            exitCode: result.exitCode
        )
    }

    private static func bounded(_ value: String) -> String {
        guard value.utf8.count > maximumOutputBytes else { return value }
        let prefix = String(decoding: value.utf8.prefix(maximumOutputBytes), as: UTF8.self)
        return prefix + "\n[output truncated at 64 KiB]\n"
    }
}

public enum CommandParser {
    public static let maximumInputBytes = 16 * 1024

    public static func parse(_ input: String) throws -> AgentCommand {
        guard input.utf8.count <= maximumInputBytes else {
            throw CommandError.invalidArguments("command input exceeds 16 KiB")
        }
        let tokens = try tokenize(input)
        guard let name = tokens.first else { throw CommandError.emptyCommand }
        return AgentCommand(name: name, arguments: Array(tokens.dropFirst()))
    }

    private static func tokenize(_ input: String) throws -> [String] {
        var result: [String] = [], current = "", quote: Character?, escaping = false, started = false
        for ch in input {
            if escaping { current.append(ch); escaping = false; started = true; continue }
            if ch == "\\" { escaping = true; started = true; continue }
            if let q = quote {
                if ch == q { quote = nil } else { current.append(ch) }
                started = true; continue
            }
            if ch == "'" || ch == "\"" { quote = ch; started = true; continue }
            if ch.isWhitespace {
                if started { result.append(current); current = ""; started = false }
            } else { current.append(ch); started = true }
        }
        if escaping { throw CommandError.invalidEscape }
        if quote != nil { throw CommandError.unterminatedQuote }
        if started { result.append(current) }
        return result
    }
}

private func parsePositiveCount(_ value: String) throws -> Int {
    guard let count = Int(value), count > 0 else { throw CommandError.invalidArguments("line count must be a positive integer") }
    return count
}

private func limitedLines(path: String, count: Int, fromStart: Bool, workspace: AgentWorkspace) async throws -> String {
    let text = try await workspace.readFile(at: path)
    let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
    let selected = fromStart ? Array(lines.prefix(count)) : Array(lines.suffix(count))
    return selected.joined(separator: "\n") + (selected.isEmpty || text.hasSuffix("\n") ? "" : "\n")
}

private func findPaths(
    under path: String,
    matching name: String?,
    workspace: AgentWorkspace,
    depth: Int = 0
) async throws -> [String] {
    guard depth < 64 else {
        throw CommandError.invalidArguments("find exceeded maximum directory depth (64)")
    }
    let entries = try await workspace.listDirectory(at: path)
    var matches: [String] = []
    for entry in entries {
        let leaf = entry.relativePath.split(separator: "/").last.map(String.init) ?? entry.relativePath
        if name == nil || leaf.localizedCaseInsensitiveContains(name!) {
            matches.append(entry.relativePath)
        }
        if entry.isDirectory {
            matches += try await findPaths(under: entry.relativePath, matching: name, workspace: workspace, depth: depth + 1)
        }
    }
    return matches.sorted()
}

private func grepMatches(pattern: String, path: String, workspace: AgentWorkspace) async throws -> String {
    guard !pattern.isEmpty else { throw CommandError.invalidArguments("grep <pattern> <file>") }
    let contents = try await workspace.readFile(at: path)
    let matches = contents.components(separatedBy: "\n").enumerated().compactMap { index, line in
        line.localizedCaseInsensitiveContains(pattern) ? "\(index + 1):\(line)" : nil
    }
    return matches.isEmpty ? "" : matches.joined(separator: "\n") + "\n"
}

public struct BuiltinCommandRegistry {
    public static func make() -> CommandRegistry {
        var registry = CommandRegistry()
        registry = registry.registering("pwd") { command, context in
            guard command.arguments.isEmpty else { throw CommandError.invalidArguments("pwd") }
            return CommandResult(stdout: (context.workingDirectory.isEmpty ? context.workspace.rootURL.path : context.workspace.rootURL.appendingPathComponent(context.workingDirectory).path) + "\n")
        }
        registry = registry.registering("ls") { command, context in
            guard command.arguments.count <= 1 else { throw CommandError.invalidArguments("ls [path]") }
            let path = command.arguments.first ?? ""
            let entries = try await context.workspace.listDirectory(at: path)
            let base = path.isEmpty ? "" : path.trimmingCharacters(in: CharacterSet(charactersIn: "/"))
            let names = entries.map { entry in
                guard !base.isEmpty, entry.relativePath.hasPrefix(base + "/") else { return entry.relativePath }
                return String(entry.relativePath.dropFirst(base.count + 1))
            }
            return CommandResult(stdout: names.joined(separator: "\n") + (names.isEmpty ? "" : "\n"))
        }
        registry = registry.registering("cat") { command, context in
            guard command.arguments.count == 1 else { throw CommandError.invalidArguments("cat <path>") }
            return CommandResult(stdout: try await context.workspace.readFile(at: command.arguments[0]))
        }
        registry = registry.registering("head") { command, context in
            guard command.arguments.count <= 2 && !command.arguments.isEmpty else { throw CommandError.invalidArguments("head <path> [lines]") }
            let count = command.arguments.count == 2 ? try parsePositiveCount(command.arguments[1]) : 10
            return CommandResult(stdout: try await limitedLines(path: command.arguments[0], count: count, fromStart: true, workspace: context.workspace))
        }
        registry = registry.registering("tail") { command, context in
            guard command.arguments.count <= 2 && !command.arguments.isEmpty else { throw CommandError.invalidArguments("tail <path> [lines]") }
            let count = command.arguments.count == 2 ? try parsePositiveCount(command.arguments[1]) : 10
            return CommandResult(stdout: try await limitedLines(path: command.arguments[0], count: count, fromStart: false, workspace: context.workspace))
        }
        registry = registry.registering("mkdir") { command, context in
            guard command.arguments.count == 1 else { throw CommandError.invalidArguments("mkdir <path>") }
            try await context.workspace.createDirectory(at: command.arguments[0]); return CommandResult()
        }
        registry = registry.registering("touch") { command, context in
            guard command.arguments.count == 1 else { throw CommandError.invalidArguments("touch <path>") }
            if !(try await context.workspace.exists(at: command.arguments[0])) {
                try await context.workspace.writeFile("", to: command.arguments[0])
            }
            return CommandResult()
        }
        registry = registry.registering("rm") { command, context in
            guard command.arguments.count == 1 else { throw CommandError.invalidArguments("rm <path>") }
            try await context.workspace.remove(at: command.arguments[0]); return CommandResult()
        }
        registry = registry.registering("cp") { command, context in
            guard command.arguments.count == 2 else { throw CommandError.invalidArguments("cp <source> <destination>") }
            try await context.workspace.copy(from: command.arguments[0], to: command.arguments[1]); return CommandResult()
        }
        registry = registry.registering("mv") { command, context in
            guard command.arguments.count == 2 else { throw CommandError.invalidArguments("mv <source> <destination>") }
            try await context.workspace.move(from: command.arguments[0], to: command.arguments[1]); return CommandResult()
        }
        registry = registry.registering("clear") { command, _ in
            guard command.arguments.isEmpty else { throw CommandError.invalidArguments("clear") }
            return CommandResult(stdout: "\u{001B}[2J\u{001B}[H")
        }
        registry = registry.registering("help") { command, _ in
            guard command.arguments.isEmpty else { throw CommandError.invalidArguments("help") }
            return CommandResult(stdout: "pwd ls cd cat head tail mkdir touch cp mv rm find grep workspace clear help\n")
        }
        for name in ["find", "grep", "agent", "skill", "module", "memory", "model", "provider", "workspace", "sync"] {
            registry = registry.registering(name) { command, _ in
                CommandResult(stderr: "command '\(command.name)' is registered but not implemented", exitCode: 127)
            }
        }
        registry = registry.registering("find") { command, context in
            guard command.arguments.count <= 2 else { throw CommandError.invalidArguments("find [path] [name-substring]") }
            let path = command.arguments.first ?? ""
            let name = command.arguments.count == 2 ? command.arguments[1] : nil
            let matches = try await findPaths(under: path, matching: name, workspace: context.workspace)
            return CommandResult(stdout: matches.isEmpty ? "" : matches.joined(separator: "\n") + "\n")
        }
        registry = registry.registering("grep") { command, context in
            guard command.arguments.count == 2 else { throw CommandError.invalidArguments("grep <pattern> <file>") }
            return CommandResult(stdout: try await grepMatches(pattern: command.arguments[0], path: command.arguments[1], workspace: context.workspace))
        }
        registry = registry.registering("workspace") { command, context in
            guard let operation = command.arguments.first else {
                throw CommandError.invalidArguments("workspace status|list [path]|read <path>|write <path> <text>|mkdir <path>|remove <path>")
            }
            let args = Array(command.arguments.dropFirst())
            switch operation {
            case "status":
                guard args.isEmpty else { throw CommandError.invalidArguments("workspace status") }
                return CommandResult(stdout: context.workspace.rootURL.path + "\n")
            case "list":
                guard args.count <= 1 else { throw CommandError.invalidArguments("workspace list [path]") }
                let entries = try await context.workspace.listDirectory(at: args.first ?? "")
                let paths = entries.map { ($0.isDirectory ? "d " : "f ") + $0.relativePath }
                return CommandResult(stdout: paths.isEmpty ? "" : paths.joined(separator: "\n") + "\n")
            case "read":
                guard args.count == 1 else { throw CommandError.invalidArguments("workspace read <path>") }
                return CommandResult(stdout: try await context.workspace.readFile(at: args[0]))
            case "write":
                guard args.count >= 2 else { throw CommandError.invalidArguments("workspace write <path> <text>") }
                let contents = args.dropFirst().joined(separator: " ")
                try await context.workspace.writeFile(contents, to: args[0])
                return CommandResult(stdout: "wrote \(contents.utf8.count) bytes\n")
            case "mkdir":
                guard args.count == 1 else { throw CommandError.invalidArguments("workspace mkdir <path>") }
                try await context.workspace.createDirectory(at: args[0])
                return CommandResult()
            case "remove":
                guard args.count == 1 else { throw CommandError.invalidArguments("workspace remove <path>") }
                try await context.workspace.remove(at: args[0])
                return CommandResult()
            default:
                throw CommandError.invalidArguments("workspace status|list [path]|read <path>|write <path> <text>|mkdir <path>|remove <path>")
            }
        }
        return registry
    }

    public static func make(skillRuntime: SkillRuntime) -> CommandRegistry {
        var registry = make()
        registry = registry.registering("skill") { command, _ in
            guard let operation = command.arguments.first else {
                throw CommandError.invalidArguments("skill list [query]|run <skill> <input>")
            }
            let args = Array(command.arguments.dropFirst())
            switch operation {
            case "list":
                guard args.count <= 1 else {
                    throw CommandError.invalidArguments("skill list [query]")
                }
                let manifests = try await skillRuntime.discover(query: args.first ?? "")
                let rows = manifests.map {
                    "\($0.id.rawValue)\t\($0.name) — \($0.description)"
                }
                return CommandResult(stdout: rows.isEmpty ? "No skills found.\n" : rows.joined(separator: "\n") + "\n")
            case "run":
                guard args.count >= 2 else {
                    throw CommandError.invalidArguments("skill run <skill> <input>")
                }
                let input = args.dropFirst().joined(separator: " ")
                let result = try await skillRuntime.run(
                    SkillExecutionRequest(
                        skillID: String(args[0]),
                        moduleID: String(args[0]),
                        input: input
                    )
                )
                return CommandResult(stdout: result)
            default:
                throw CommandError.invalidArguments("skill list [query]|run <skill> <input>")
            }
        }
        registry = registry.registering("help") { command, _ in
            guard command.arguments.isEmpty else { throw CommandError.invalidArguments("help") }
            return CommandResult(stdout: "pwd ls cd cat head tail mkdir touch cp mv rm find grep workspace skill clear help\n")
        }
        return registry
    }
}
